FROM golang:1.16.4-alpine

RUN apk update -qq && apk add curl

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o /bin/app ./src/api

EXPOSE 8080

CMD ["/bin/app"]
