version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "air"
    env_file:
      - .env.development
    volumes:
      - ${PWD}:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbitmq
      - mongo
  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    volumes:
      - bongster88-db:/var/lib/postgresql
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=bongster88
      - POSTGRES_PASSWORD=bongster88
      - POSTGRES_DB=bongster88

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: unless-stopped
    ports:
      - 15672:15672
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - bongster88-mq:/data
    environment:
      - RABBITMQ_NODENAME=node@rabbitmq
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - bonster88-mongo:/data/db

volumes: 
  bongster88-db:
    driver: local
  bonster88-mongo:
    driver: local
  bongster88-mq:
    driver: local
