version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "air"
    env_file:
      - .env.development
    volumes:
      - ${PWD}:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbitmq
  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    volumes:
      - bongster88-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=bongster88
      - POSTGRES_PASSWORD=bongster88
      - POSTGRES_DB=bongster88
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    volumes:
      - bongster88-mq:/data
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_NODENAME=node@rabbitmq
volumes:
  bongster88-db:
    driver: local
  bongster88-mq:
    driver: local
