GET http://localhost:8080/TaskGroups HTTP/1.1
content-type: application/json

GET http://localhost:8080/chats HTTP/1.1
content-type: application/json

POST http://localhost:8080/chats HTTP/1.1
content-type: application/json


